version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.13.0
    working_directory: /home/circleci/app
    steps:
      - checkout

      - restore_cache:
          key: v1-dep-{{ checksum "yarn.lock" }}

      - run:
          name: Install deps
          command: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - ./node_modules
            - ~/.cache
          key: v1-dep-{{ checksum "yarn.lock" }}

      - run:
          name: Run tests
          command: yarn test

      - run:
          name: Run build
          command: yarn build

      - run:
          name: Run codechecks
          # we use local version of a client
          command: DEBUG=* ./packages/client/dist/runner.js

workflows:
  version: 2
  build:
    jobs:
      - build
